# Netlify configuration for TSLA Stock Dashboard

[build]
  # Build command (runs when you deploy)
  command = "npm run build"
  # The directory containing your built files (Vite's output)
  publish = "dist"
  # We're not using Netlify Functions, so this can be removed
  # functions = "functions"

# Environment variables
[build.environment]
  NODE_VERSION = "18"  # Match your local Node.js version
  VITE_API_BASE_URL = ""  # Will be overridden by Netlify UI settings

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to the Render backend
[[redirects]]
  from = "/api/*"
  to = "https://your-render-app.onrender.com/api/:splat"  # Replace with your Render backend URL
  status = 200
  force = true

# CORS headers
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https://your-render-app.onrender.com;"

# Environment variable configuration
[context.production.environment]
  VITE_GEMINI_API_URL = "/api"

[context.deploy-preview.environment]
  VITE_GEMINI_API_URL = "/api"

[context.branch-deploy.environment]
  VITE_GEMINI_API_URL = "/api"
