services:
  - type: web
    name: tsla-dashboard
    env: node
    buildCommand: |
      # Clean environment
      rm -rf node_modules package-lock.json .npmrc
      npm cache clean --force
      
      # Update npm
      npm install -g npm@latest
      
      # Install Vite globally and locally
      npm install -g vite@latest
      npm install vite@latest --save-dev
      
      # Install project dependencies
      npm install --force
      
      # Run build with Node.js flags for ES modules
      node --experimental-modules --experimental-json-modules node_modules/vite/bin/vite.js build --config vite.config.js
      
      # Prepare for deployment
      npm run prepare-deploy
    startCommand: cd deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        fromDatabase:
          name: gemini-api-key
          property: value
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health
