services:
  - type: web
    name: tsla-dashboard
    env: node
    buildCommand: |
      rm -rf node_modules package-lock.json .npmrc
      npm install -g npm@latest
      npm install vite --save-exact
      npm install --force
      export PATH="./node_modules/.bin:$PATH" && npm run build
      npm run prepare-deploy
    startCommand: cd deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        fromDatabase:
          name: gemini-api-key
          property: value
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health
