services:
  - type: web
    name: tsla-dashboard
    env: node
    buildCommand: |
      # Clean environment
      rm -rf node_modules package-lock.json .npmrc
      npm cache clean --force
      
      # Install dependencies and build
      npm install --legacy-peer-deps --force
      npm run build
      
      # Prepare for deployment
      npm run prepare-deploy
    startCommand: cd deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        fromDatabase:
          name: gemini-api-key
          property: value
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health
