services:
  - type: web
    name: tsla-dashboard
    env: node
    buildCommand: |
      # Clean environment
      rm -rf node_modules package-lock.json .npmrc
      npm cache clean --force
      
      # Install exact versions from package-lock.json
      npm ci --legacy-peer-deps
      
      # Build the frontend using the specific vite-build script
      npm run vite-build
      
      # Prepare for deployment
      npm run prepare-deploy
    
    startCommand: npm start
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        fromDatabase:
          name: gemini-api-key
          property: value
      - key: FRONTEND_URL
        value: https://tsla-stock-dashboard.onrender.com
    
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    
    # Configure build cache
    buildCache:
      paths:
        - node_modules
    
    # Configure build timeout (in seconds)
    buildTimeout: 600
