services:
  - type: web
    name: tsla-dashboard
    env: node
    buildCommand: |
      # Clean environment
      rm -rf node_modules package-lock.json .npmrc
      npm cache clean --force
      
      # Install all dependencies including devDependencies
      npm install --legacy-peer-deps --force --include=dev
      
      # Install Vite globally
      npm install -g vite@5.4.19
      
      # Verify PostCSS configuration
      if [ -f postcss.config.js ]; then
        echo "PostCSS config found at $(pwd)/postcss.config.js"
      else
        echo "No PostCSS config found, creating one..."
        echo 'export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};' > postcss.config.js
      fi
      
      # Build the project
      npm run build
      
      # Prepare for deployment
      npm run prepare-deploy
    startCommand: cd deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        fromDatabase:
          name: gemini-api-key
          property: value
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health
