services:
  - type: web
    name: tsla-dashboard
    env: node
    buildCommand: |
      # Clean environment
      rm -rf node_modules package-lock.json .npmrc
      npm cache clean --force
      
      # Install all dependencies
      npm install --legacy-peer-deps
      
      # Build the frontend
      npm run vite-build
      
      # Install production dependencies in deploy directory
      cd deploy
      npm install --production
      cd ..
      
      # Ensure node_modules is in the right place
      if [ ! -d "deploy/node_modules" ]; then
        echo "Moving node_modules to deploy directory..."
        mv node_modules deploy/
      fi
    
    startCommand: npm start
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        fromDatabase:
          name: gemini-api-key
          property: value
      - key: FRONTEND_URL
        value: https://tsla-stock-dashboard.onrender.com
    
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    
    # Configure build cache
    buildCache:
      paths:
        - node_modules
    
    # Configure build timeout (in seconds)
    buildTimeout: 600
